services:
  db:
    image: mysql:8.0
    container_name: model_db
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./database/db_data:/var/lib/mysql
      
  nginx:
    build: ./django-app/nginx
    container_name: proxy-server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./django-app/app/static/:/usr/share/nginx/static/
    depends_on:
      - web
      - db

  web:
    build: ./django-app
    container_name: web-interface
    restart: always
    depends_on:
      - db
    environment:
      DEBUG: 0
      DB_NAME: mydb
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306
      SECRET_KEY: ad9e4698-6688-42a7-9832-ab1fde21728f
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    
    #command: sh -c "pip install --no-cache-dir -r requirements.txt && daphne -b 0.0.0.0 -p 8000 web_interface.asgi:application"
    ports:
      - "8000:8000"
    volumes:
      - ./django-app:/app