# Generated by Django 5.2.7 on 2025-10-22 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('gameID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='No Name', max_length=256, unique=True)),
                ('studio', models.CharField(blank=True, max_length=256, null=True)),
                ('releaseYear', models.SmallIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('albumName', models.CharField(blank=True, max_length=128, null=True)),
                ('composer', models.CharField(blank=True, max_length=128, null=True)),
                ('gameID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.games')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('songID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('songName', models.CharField(blank=True, max_length=128, null=True)),
                ('albumID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.album')),
                ('gameID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.games')),
            ],
        ),
        migrations.CreateModel(
            name='FavSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('songID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.songs')),
            ],
        ),
    ]
