# Generated by Django 5.2.7 on 2025-10-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_games_album_songs_favsongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='length',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='songs',
            name='videoURL',
            field=models.URLField(blank=True, default='', max_length=512, null=True),
        ),
    ]
