# Generated by Django 5.2.7 on 2025-11-14 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_songs_albumid_delete_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTypes',
            fields=[
                ('badgeTypeID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('badgeName', models.CharField(default='No Name', max_length=128)),
                ('badgeDesc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('roleID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('roleName', models.CharField(default='No Name', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='favsongs',
            name='songID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.songs'),
        ),
        migrations.AlterField(
            model_name='favsongs',
            name='userID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songs',
            name='gameID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.games'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='UserBadges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badgeTypeID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.badgetypes')),
                ('userID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.userroles'),
        ),
    ]
