# Generated by Django 5.2.8 on 2025-11-22 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_badgetypes_userroles_alter_favsongs_songid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('commentText', models.TextField(default='', max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('songID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.songs')),
                ('userID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
