# Generated by Django 5.2.7 on 2025-11-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_badgetypes_userroles_alter_favsongs_songid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], default='guest', max_length=10),
        ),
        migrations.AddField(
            model_name='songs',
            name='imageURL',
            field=models.URLField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
