# Generated by Django 6.0 on 2025-12-06 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_role_songs_imageurl_delete_userroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favsongs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userbadges',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('commentText', models.TextField(default='', max_length=512)),
                ('commentTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('gameID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.games')),
                ('userID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
