# Generated by Django 5.2.8 on 2025-11-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='timestamp',
        ),
    ]
