# Generated by Django 5.2.7 on 2025-11-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_role_songs_imageurl_delete_userroles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='games',
            name='imageURL',
            field=models.URLField(blank=True, default='', max_length=512, null=True),
        ),
    ]
