# Generated by Django 5.2.8 on 2025-11-22 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_comments_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='songID',
        ),
        migrations.AddField(
            model_name='comments',
            name='gameID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.games'),
        ),
    ]
