# Generated by Django 6.0 on 2025-12-22 15:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_songs_imageurl_games_imageurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='comments',
            name='isReply',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Reply'),
        ),
        migrations.AddField(
            model_name='comments',
            name='replyCommentID',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Reply Comment ID'),
        ),
        migrations.AddField(
            model_name='games',
            name='imageURL',
            field=models.URLField(blank=True, default='', max_length=512, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='badgetypes',
            name='badgeDesc',
            field=models.TextField(blank=True, null=True, verbose_name='Badge Description'),
        ),
        migrations.AlterField(
            model_name='badgetypes',
            name='badgeName',
            field=models.CharField(default='No Name', max_length=128, verbose_name='Badge Name'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentText',
            field=models.TextField(default='', max_length=512, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Comment Time'),
        ),
        migrations.AlterField(
            model_name='games',
            name='genre',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='games',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='games',
            name='releaseYear',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Release Year'),
        ),
        migrations.AlterField(
            model_name='games',
            name='studio',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Studio'),
        ),
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(default='No Name', max_length=256, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='length',
            field=models.DurationField(blank=True, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='songName',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Song Name'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='videoURL',
            field=models.URLField(blank=True, default='', max_length=512, null=True, verbose_name='Video URL'),
        ),
        migrations.CreateModel(
            name='LikedComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.comments')),
                ('userID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
