# Generated by Django 5.2.8 on 2025-11-23 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_comments_songid_comments_gameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commentTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
