# Generated by Django 6.0 on 2025-12-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_songs_imageurl_comments_isreply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.BigIntegerField(default=0, verbose_name='Likes'),
        ),
    ]
