# Generated by Django 6.0 on 2025-12-22 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_comments_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedcomments',
            name='commentID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comments'),
        ),
        migrations.AlterField(
            model_name='likedcomments',
            name='userID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
