# Generated by Django 6.0 on 2025-12-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_likedcomments_commentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='replyCommentID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comments'),
        ),
    ]
